version: "3.8"

services: 
  backend:
    build: "./server"
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal
    depends_on:
      - redis
    networks:
        - app_network

  frontend:
    build: "./livego"
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
        - app_network

  redis:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
        - app_network


networks:
  app_network:
    driver: bridge
